project/admin/categories/forms.py
from wtforms import Form, StringField


class CategoryForm(Form):
    name = StringField('Название')
    slug = StringField('Slug')

project/admin/categories/blueprint.py
from flask import Blueprint, render_template
from flask import request, flash
from flask import redirect, url_for
from flask_security import login_required

from models.category import Category
from .forms import CategoryForm

from shared import db

categories = Blueprint('categories', __name__)


@categories.route('/')
@login_required
def index():
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    categories = Category.query.order_by(Category.id.desc())
    pages = categories.paginate(page=page, per_page=10)

    return render_template('categories/index.html', pages=pages)


@categories.route('/create', methods=['POST', 'GET'])
@login_required
def create():

    if request.method == 'POST':

        name = request.form['name']
        slug = request.form['slug']

        try:
            category = Category(name=name, slug=slug)
            db.session.add(category)
            db.session.commit()
            return redirect(url_for('categories.index'))
        except Exception as exc:
            db.session.rollback()
            flash(exc.message, 'danger')
            print('Error', exc)

    form = CategoryForm()
    return render_template('categories/create.html', form=form)


@categories.route('/<id>/edit', methods=['POST', 'GET'])
@login_required
def edit(id):
    category = Category.query.filter(Category.id == id).first()

    if request.method == 'POST':
        form = CategoryForm(formdata=request.form, obj=category)
        form.populate_obj(category)
        db.session.commit()
        return redirect(url_for('categories.index'))

    form = CategoryForm(obj=category)
    return render_template('categories/edit.html', category=category, form=form)


@categories.route('/<id>/delete')
@login_required
def delete(id):
    Category.query.filter(Category.id == id).delete()
    db.session.commit()
    flash('Категория удалена', 'success')
    return redirect(url_for('categories.index'))

project/admin/templates/categories/create.html
{% extends 'admin/base.html' %}

{% block title %}
  Добавление категории
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Посты</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Добавление категории</h6>
          </div>
          <div class="card-body">
            <form class="user" action="{{ url_for('categories.create') }}" method="POST" enctype="multipart/form-data">
              {{ form.csrf_token }}

              {% for field in form %}

              <div class="form-group">
                  {{ field.label() }}
                  {{ field(class='form-control') }}
              </div>

              {% endfor %}

              <button class="btn btn-primary btn-user btn-block">Сохранить</button>
            
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

project/admin/templates/categories/edit.html
{% extends 'admin/base.html' %}

{% block title %}
  {{ category.name }}
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Категории</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Редактирование категории</h6>
          </div>
          <div class="card-body">
            

            <form class="user" action="{{ url_for('categories.edit', id=category.id) }}" method="POST" enctype="multipart/form-data">
              {{ form.csrf_token }}

              {% for field in form %}
              <div class="form-group">
                  {{ field.label() }}
                  {{ field(class='form-control') }}
              </div>
              {% endfor %}

              <button class="btn btn-primary btn-user btn-block">Сохранить</button>
            
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

project/admin/templates/categories/index.html
{% extends 'admin/base.html' %}

{% block title %}
  Категории
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Категории</h1>
      <a href="{{ url_for('categories.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Добавить категорию
      </a>
    </div>

    <!-- Content Row -->
    <div class="row">
      <table class="table col-lg-6">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Slug</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for category in pages.items %}
          <tr>
            <th scope="row">{{ category.id }}</th>
            <td>{{ category.name }}</td>
            <td>{{ category.slug }}</td>
            <td>
              <div class="btn-group btn-group-sm float-right" role="group" aria-label="...">
                <a href="{{ url_for('categories.edit', id=category.id) }}" class="btn btn-warning btn-sm btn-icon-split">
                  <span class="text-white">
                    <i class="fas fa-edit"></i>
                  </span>
                </a>
    
                <a href="{{ url_for('categories.delete', id=category.id) }}" class="btn btn-danger btn-sm btn-icon-split">
                  <span class="text-white">
                    <i class="fas fa-trash-alt"></i>
                  </span>
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
        </table>

      <nav class="col-lg-12 mb-4">
        <ul class="pagination">

          <li {% if not pages.has_prev %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.prev_num }}">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %}class="page-item active"{% else %}class="page-item"{% endif %}>
              <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
            </li>
          {% endfor %}

          <li {% if not pages.has_next %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.next_num }}">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
{% endblock %}