project/admin/users/forms.py
from wtforms import Form, StringField, BooleanField, PasswordField, widgets
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField

from models.role import Role

def enabled_roles():
    return Role.query.all()

class UserForm(Form):
    username = StringField('Логин')
    email = StringField('Email')
    password = PasswordField('Пароль')
    active = BooleanField('Активен')
    roles = QuerySelectMultipleField(
        'Роль',
        query_factory=enabled_roles,
        get_label=lambda role: role.name,
        widget=widgets.ListWidget(prefix_label=False),
        option_widget=widgets.CheckboxInput()
    )

project/admin/users/blueprint.py
from flask import Blueprint, render_template, flash
from flask import request
from flask import redirect, url_for
from flask_security import login_required, roles_required

from models.user import User
from .forms import UserForm

from shared import db

users = Blueprint('users', __name__)


@users.route('/')
@login_required
@roles_required('admin')
def index():
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    users = User.query.order_by(User.created_at.desc())
    pages = users.paginate(page=page, per_page=10)

    return render_template('users/index.html', pages=pages)


@users.route('/create', methods=['POST', 'GET'])
@login_required
@roles_required('admin')
def create():

    if request.method == 'POST':

        form_post = UserForm(request.form)
        print(form_post)

        try:
            user = User(
                username=form_post.username.data, email=form_post.email.data,
                password=form_post.password.data, active=form_post.active.data,
                roles=form_post.roles.data
            )
            print(user)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('users.index'))
        except Exception as exc:
            db.session.rollback()
            flash(exc.message, 'danger')
            print('Error', exc)

    form = UserForm()
    return render_template('users/create.html', form=form)


@users.route('/<id>/edit', methods=['POST', 'GET'])
@login_required
@roles_required('admin')
def edit(id):
    user = User.query.filter(User.id == id).first()

    if request.method == 'POST':
        form = UserForm(formdata=request.form, obj=user)
        form.populate_obj(user)
        db.session.commit()
        return redirect(url_for('users.index'))

    form = UserForm(obj=user)
    return render_template('users/edit.html', user=user, form=form)


@users.route('/<id>')
@login_required
def detail(id):
    user = User.query.filter(User.id == id).first()
    return render_template('users/detail.html', user=user)


@users.route('/<id>/delete')
@login_required
@roles_required('admin')
def delete(id):
    user = User.query.filter(User.id == id).first()
    user.delete()
    flash('Пользователь удален', 'success')
    return redirect(url_for('users.index'))

project/admin/templates/users/create.html
{% extends 'admin/base.html' %}

{% block title %}
  Добавление пользователя
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Пользователь</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Добавление пользователя</h6>
          </div>
          <div class="card-body">
            

            <form class="user" action="{{ url_for('users.create') }}" method="POST" enctype="multipart/form-data">
              {{ form.csrf_token }}

              {% for field in form %}

              <div class="form-group">

                {% if field.type == "BooleanField" %}
                  <div class="custom-control custom-checkbox small">
                    {{ field(class='custom-control-input') }}
                    {{ field.label(class='custom-control-label') }}
                  </div>
                {% elif field.type == "QuerySelectMultipleField" %}
                  {{ field.label(class='form-control-file') }}
    
                  {% for subfield in field %}
                    <div class="custom-control custom-checkbox">
                      {{ subfield(class='custom-control-input') }}
                      {{ subfield.label(class='custom-control-label') }}
                    </div>
                  {% endfor %}
                {% else %}
                  {{ field.label() }}
                  {{ field(class='form-control') }}
                {% endif %}

              </div>

              {% endfor %}

              <button class="btn btn-primary btn-user btn-block">Сохранить</button>
            
            </form>

            {{ ckeditor.load() }}
            {{ ckeditor.config(name='body') }}

          </div>
        </div>
      </div>
    </div>
{% endblock %}

project/admin/templates/users/edit.html
{% extends 'admin/base.html' %}

{% block title %}
  {{ user.username }}
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Пользователи</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Редактирование</h6>
          </div>
          <div class="card-body">
            

            <form class="user" action="{{ url_for('users.edit', id=user.id) }}" method="POST">
              {{ form.csrf_token }}

              {% for field in form %}

              <div class="form-group">

                {% if field.type == "BooleanField" %}
                  <div class="custom-control custom-checkbox small">
                    {{ field(class='custom-control-input') }}
                    {{ field.label(class='custom-control-label') }}
                  </div>
                {% elif field.type == "QuerySelectMultipleField" %}
                  {{ field.label(class='form-control-file') }}
    
                  {% for subfield in field %}
                    <div class="custom-control custom-checkbox">
                      {{ subfield(class='custom-control-input') }}
                      {{ subfield.label(class='custom-control-label') }}
                    </div>
                  {% endfor %}
                {% else %}
                  {{ field.label() }}
                  {{ field(class='form-control') }}
                {% endif %}

              </div>

              {% endfor %}

              <button class="btn btn-primary btn-user btn-block">Сохранить</button>
            
            </form>

          </div>
        </div>
      </div>
    </div>
{% endblock %}

project/admin/templates/users/index.html
{% extends 'admin/base.html' %}

{% block title %}
    Пользователи
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Пользователи</h1>
      <a href="{{ url_for('users.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Добавить пользователя
      </a>
    </div>

    <!-- Content Row -->
    <div class="row">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Логин</th>
            <th scope="col">Email</th>
            <th scope="col">Последний вход</th>
            <th scope="col">IP</th>
            <th scope="col">Статус</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for user in pages.items %}
          <tr>
            <th scope="row">{{ user.id }}</th>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ moment(user.current_login_at).format('Do.MM.Y HH:mm') }}</td>
            <td>{{ user.current_login_ip }}</td>
            <td>{% if user.active %}
              <span class="btn btn-success btn-circle btn-sm"></span>
              {% else %}
              <span class="btn btn-danger btn-circle btn-sm"></span>
              {% endif %}
            </td>
            <td>
              <div class="btn-group btn-group-sm float-right" role="group" aria-label="...">
                <a href="{{ url_for('users.edit', id=user.id) }}" class="btn btn-warning btn-sm btn-icon-split">
                  <span class="text-white">
                    <i class="fas fa-edit"></i>
                  </span>
                </a>
    
                <a href="{{ url_for('users.delete', id=user.id) }}" class="btn btn-danger btn-sm btn-icon-split">
                  <span class="text-white">
                    <i class="fas fa-trash-alt"></i>
                  </span>
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
        </table>

      <nav class="col-lg-12 mb-4">
        <ul class="pagination">

          <li {% if not pages.has_prev %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.prev_num }}">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %}class="page-item active"{% else %}class="page-item"{% endif %}>
              <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
            </li>
          {% endfor %}

          <li {% if not pages.has_next %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.next_num }}">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
{% endblock %}