project/models/category.py
import re
from shared import db


def slugify(str):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', str).lower()


class Category(db.Model):
    __tablename__ = 'categories'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    slug = db.Column(db.String(100), nullable=False, unique=True)

    posts = db.relationship('Post', backref='category', lazy='dynamic')

    def __init__(self, *args, **kwargs):
        super(Category, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Category #{self.id} {self.name}>'

project/models/post.py
from shared import db
from datetime import datetime
from flask_login import current_user
import re

from models.post_tags import post_tags
from models.post_comments import post_comments


def slugify(str):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', str).lower()


class Post(db.Model):
    from models import User, Category

    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140), nullable=False)
    slug = db.Column(db.String(140), nullable=False, unique=True)
    text = db.Column(db.Text, nullable=False)
    photo = db.Column(db.String(255), unique=True)
    is_published = db.Column(db.Boolean, nullable=False, default=False, server_default='0')
    user_id = db.Column(db.Integer,
                        db.ForeignKey(User.id, onupdate="CASCADE", ondelete="CASCADE"),
                        nullable=False)
    category_id = db.Column(db.Integer,
                            db.ForeignKey(Category.id, onupdate="CASCADE", ondelete="CASCADE"),
                            nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.now())
    published_at = db.Column(db.DateTime, default=datetime.now())

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy="dynamic"))
    comments = db.relationship('Comment', secondary=post_comments, backref=db.backref('post', lazy="dynamic"))

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def is_owner(self):
        return self.author == current_user

    def __repr__(self):
        return f'<Post #{self.id} {self.title}>'

project/admin/categories/forms.py
from wtforms import Form, StringField


class CategoryForm(Form):
    name = StringField('Название')
    slug = StringField('Slug')

project/admin/categories/blueprint.py
from flask import Blueprint, render_template
from flask import request, flash
from flask import redirect, url_for
from flask_security import login_required

from models.category import Category
from .forms import CategoryForm

from shared import db

categories = Blueprint('categories', __name__)


@categories.route('/')
@login_required
def index():
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    categories = Category.query.order_by(Category.id.desc())
    pages = categories.paginate(page=page, per_page=10)

    return render_template('categories/index.html', pages=pages)


@categories.route('/create', methods=['POST', 'GET'])
@login_required
def create():

    if request.method == 'POST':

        name = request.form['name']
        slug = request.form['slug']

        try:
            category = Category(name=name, slug=slug)
            db.session.add(category)
            db.session.commit()
            return redirect(url_for('categories.index'))
        except Exception as exc:
            db.session.rollback()
            flash(exc.message, 'danger')
            print('Error', exc)

    form = CategoryForm()
    return render_template('categories/create.html', form=form)


@categories.route('/<id>/edit', methods=['POST', 'GET'])
@login_required
def edit(id):
    category = Category.query.filter(Category.id == id).first()

    if request.method == 'POST':
        form = CategoryForm(formdata=request.form, obj=category)
        form.populate_obj(category)
        db.session.commit()
        return redirect(url_for('categories.index'))

    form = CategoryForm(obj=category)
    return render_template('categories/edit.html', category=category, form=form)


@categories.route('/<id>/delete')
@login_required
def delete(id):
    Category.query.filter(Category.id == id).delete()
    db.session.commit()
    flash('Категория удалена', 'success')
    return redirect(url_for('categories.index'))

project/admin/posts/blueprint.py
import os

from flask import Blueprint, render_template
from flask import request, flash
from flask import redirect, url_for
from flask_security import login_required, roles_required
from flask_login import current_user


from models import Post
from forms import PostForm, enabled_tags

from shared import db
from app import app

posts = Blueprint('posts', __name__, template_folder='admin/templates')


@posts.route('/')
@login_required
@roles_required('admin')
def index():
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    posts = Post.query.order_by(Post.id.desc())
    pages = posts.paginate(page=page, per_page=5)

    return render_template('admin/posts/index.html', pages=pages)


@posts.route('/create', methods=['POST', 'GET'])
@login_required
@roles_required('admin')
def create():

    if request.method == 'POST':

        form_post = PostForm(request.form)
        photo = form_post.upload_photo()

        if not photo:
            return redirect(request.url)

        try:
            post = Post(
                title=form_post.title.data, text=form_post.text.data,
                is_published=form_post.is_published.data, tags=form_post.tags.data,
                category=form_post.category.data, photo=photo,
                author=current_user
            )
            db.session.add(post)
            db.session.commit()

            flash('Пост добавлен', 'success')
            return redirect(url_for('posts.index'))
        except Exception as exc:
            db.session.rollback()
            flash(exc.message, 'danger')
            print('Error', exc)

    form = PostForm()
    return render_template('admin/posts/create.html', form=form)


@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
@roles_required('admin')
def edit(slug):
    post = Post.query.filter(Post.slug == slug).first()
    form = PostForm(obj=post)

    if request.method == 'POST':

        if form.valid_photo():
            post.photo = form.upload_photo(post.photo)

        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.detail', slug=post.slug))

    return render_template('admin/posts/edit.html', post=post, form=form)


@posts.route('/<id>/delete')
@login_required
@roles_required('admin')
def delete(id):
    post = Post.query.filter(Post.id == id).first()
    os.remove(os.path.join(app.config['UPLOAD_FOLDER'], post.photo))
    post.delete()
    flash('Пост удален', 'success')
    return render_template('admin/posts/index.html')


@posts.route('/<slug>')
@login_required
@roles_required('admin')
def detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    return render_template('admin/posts/detail.html', post=post, tags=enabled_tags)

project/posts/blueprint.py
import os

from flask import Blueprint, render_template
from flask import request, flash
from flask import redirect, url_for
from flask_security import login_required, roles_required
from flask_login import current_user
from sqlalchemy import and_

from models import Post, Comment, Category, Tag
from forms import CommentForm, PostForm, enabled_tags

from shared import db
from app import app

user_posts = Blueprint('user_posts', __name__)


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']


@user_posts.route('/my')
@login_required
def my():
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    posts = Post.query.filter(Post.user_id == current_user.id).order_by(Post.id.desc())
    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', pages=pages)


@user_posts.route('/')
def index():
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    posts = Post.query.filter(Post.is_published == 1).order_by(Post.id.desc())
    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/all.html', pages=pages)


@user_posts.route('/category/<slug>')
def category(slug):
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    posts = Post.query.join(Post.category).filter(and_(Post.is_published == 1), (Category.slug == slug))\
        .order_by(Post.id.desc())
    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/category.html', pages=pages)


@user_posts.route('/tag/<slug>')
def tag(slug):
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    posts = Post.query.join(Post.tags).filter(and_(Post.is_published == 1), (Tag.slug == slug))\
        .order_by(Post.id.desc())
    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/category.html', pages=pages)


@user_posts.route('/create', methods=['POST', 'GET'])
@login_required
@roles_required('user')
def create():

    if request.method == 'POST':

        form_post = PostForm(request.form)
        photo = form_post.upload_photo()

        if not photo:
            return redirect(request.url)

        try:
            post = Post(
                title=form_post.title.data, text=form_post.text.data,
                is_published=form_post.is_published.data, tags=form_post.tags.data,
                category=form_post.category.data, photo=photo,
                author=current_user
            )
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('user_posts.my'))
        except Exception as exc:
            db.session.rollback()
            flash(exc.message, 'danger')
            print('Error', exc)

    form = PostForm()
    return render_template('posts/create.html', form=form)


@user_posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
@roles_required('user')
def edit(slug):
    post = Post.query.filter(Post.slug == slug).first()

    if not post.is_owner():
        flash('Вы можете редактировать только свои посты', 'danger')
        return redirect(url_for('user_posts.index'))

    form = PostForm(obj=post)

    if request.method == 'POST':

        if form.valid_photo():
            post.photo = form.upload_photo(post.photo)

        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('user_posts.detail', slug=post.slug))

    return render_template('posts/edit.html', post=post, form=form)


@user_posts.route('/<id>/delete')
@login_required
@roles_required('user')
def delete(id):
    post = Post.query.filter(Post.id == id).first()

    if post is None:
        flash('Данный пост не существует', 'danger')
        return redirect(url_for('user_posts.my'))

    if not post.is_owner():
        flash('Вы можете редактировать только свои посты', 'danger')
        return redirect(url_for('user_posts.my'))

    os.remove(os.path.join(app.config['UPLOAD_FOLDER'], post.photo))
    post.delete()
    flash('Пост удален', 'success')
    return render_template('posts/index.html')


@user_posts.route('/<slug>', methods=['POST', 'GET'])
def detail(slug):
    post = Post.query.filter(and_(Post.is_published == 1), (Post.slug == slug)).first()
    posts = Post.query.filter(Post.slug != slug).order_by(Post.id.desc()).limit(3)

    if request.method == 'POST' and current_user.is_authenticated:

        comment_post = CommentForm(request.form)

        try:
            comment = Comment(
                text=comment_post.text.data
            )
            comment.author = current_user

            db.session.add(comment)
            post.comments.append(comment)
            db.session.add(post)
            db.session.commit()
        except Exception as exc:
            db.session.rollback()
            flash(exc.message, 'danger')
            print('Error', exc)

    form = CommentForm()
    return render_template('posts/detail.html', post=post, tags=enabled_tags, posts=posts, form=form)

project/templates/posts/all.html
{% extends 'base.html' %}

{% block title %}
    All posts
{% endblock %}

{% block body %}
    <main>
        <section class="container posts">
            <h2 class="d-none">All posts</h2>

            {% if pages.items %}
                <div class="row post-wrapper">
                    {% for post in pages.items %}
                        <article class="card post col-xs-12 col-lg-6">
                            {% if post.photo %}
                                <div class="card-img-top">
                                    <img class="img-fluid" src="/static/{{ post.photo }}" alt="{{post.title}}">
                                </div>
                            {% endif %}

                            <div class="card-body">
                                {% if post.tags %}
                                    <div class="mb-2">
                                    {% for tag in post.tags %}
                                        <a href="{{ url_for('user_posts.tag', slug=tag.slug) }}" class="badge badge-{{tag.get_color()}}">
                                            {{tag.name}}
                                        </a>
                                    {% endfor %}
                                    </div>
                                {% endif %}

                                {% if post.category %}
                                    <a class="post-category" href="{{ url_for('user_posts.category', slug=post.category.slug) }}">
                                        {{ post.category.name }}
                                    </a>
                                {% endif %}

                                <h3 class="post-title">
                                    <a class="post-link" href="{{ url_for('user_posts.detail', slug=post.slug) }}">
                                        {{ post.title }}
                                    </a>
                                </h3>

                                <p class="card-text">{{ post.text|striptags|truncate(150) }}</p>
                            </div>
                        </article>
                    {% endfor %}
                </div>
            {% endif %}

            <nav class="container mb-4">
                <ul class="pagination">
      
                  <li {% if not pages.has_prev %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
                    <a class="page-link" href="./?page={{ pages.prev_num }}">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a>
                  </li>
      
                  {% for page in pages.iter_pages() %}
                    <li {% if page == pages.page %}class="page-item active"{% else %}class="page-item"{% endif %}>
                      <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
                    </li>
                  {% endfor %}
      
                  <li {% if not pages.has_next %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
                    <a class="page-link" href="./?page={{ pages.next_num }}">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Next</span>
                    </a>
                  </li>
                </ul>
            </nav>
        </section>
    </main>
{% endblock %}

project/templates/posts/category.html
{% extends 'base.html' %}

{% block title %}
    Посты
{% endblock %}

{% block body %}
<main>
  <section class="container posts">
      <h2 class="d-none">Category posts</h2>

      <div class="row post-wrapper">
        {% for post in pages.items %}
              <article class="card post col-xs-12 col-lg-6">
                  {% if post.photo %}
                      <img class="card-img-top img-fluid" src="/static/{{ post.photo }}" alt="{{post.title}}">
                  {% endif %}

                  <div class="card-body">
                    {% if post.tags %}
                        <div class="mb-2">
                        {% for tag in post.tags %}
                            <a href="{{ url_for('user_posts.tag', slug=tag.slug) }}" class="badge badge-{{tag.get_color()}}">
                                {{tag.name}}
                            </a>
                        {% endfor %}
                        </div>
                    {% endif %}

                    {% if post.category %}
                        <a class="post-category" href="{{ url_for('user_posts.category', slug=post.category.slug) }}">
                            {{ post.category.name }}
                        </a>
                    {% endif %}

                      <h3 class="post-title">
                          <a class="post-link" href="{{ url_for('user_posts.detail', slug=post.slug) }}">
                              {{ post.title }}
                          </a>
                      </h3>

                      <p class="card-text">{{ post.text|striptags|truncate(150) }}</p>
                  </div>
              </article>
          {% endfor %}
      </div>

      <nav class="col-lg-12 mb-4">
        <ul class="pagination">

          <li {% if not pages.has_prev %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.prev_num }}">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %}class="page-item active"{% else %}class="page-item"{% endif %}>
              <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
            </li>
          {% endfor %}

          <li {% if not pages.has_next %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.next_num }}">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
  </section>
  </main>
{% endblock %}

project/templates/posts/create.html
{% extends 'base.html' %}

{% block title %}
  Добавление поста
{% endblock %}

{% block body %}

{% include '_toasts.html' %}

<main>
  <section class="container single-post">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Добавление поста</h6>
      </div>
      <div class="card-body">
        <form class="edit" action="{{ url_for('user_posts.create') }}" method="POST" enctype="multipart/form-data">
          {{ form.csrf_token }}

          {% for field in form %}

          <div class="form-group">
            {% if field.type == "BooleanField" %}
              <div class="custom-control custom-checkbox">
                {{ field(class='custom-control-input') }}
                {{ field.label(class='custom-control-label') }}
              </div>
            {% elif field.type == "QuerySelectMultipleField" %}
              {{ field.label(class='form-control-file') }}

              {% for subfield in field %}
                <div class="custom-control custom-checkbox">
                  {{ subfield(class='custom-control-input') }}
                  {{ subfield.label(class='custom-control-label') }}
                </div>
              {% endfor %}
            {% elif field.type == "FileField" %}
                {{ field.label(class='form-control-file') }}
                {{ field() }}
            {% else %}
              {{ field.label() }}
              {{ field(class='form-control') }}
            {% endif %}
          </div>

          {% endfor %}

          <button class="btn btn-primary btn-user btn-block">Сохранить</button>
        </form>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
      </div>
    </div>
  </section>
</main>
{% endblock %}

project/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block body %}
  <main>
    <section class="container single-post">
        <h2 class="d-none">{{ post.title }}</h2>

        <article class="card post-main">
            {% if post.photo %}
                <div class="card-img-top">
                    <img class="img-fluid" src="/static/{{ post.photo }}" alt="{{post.title}}">
                </div>
            {% endif %}

            <div class="card-body">
              {% if post.tags %}
                  <div class="mb-2">
                  {% for tag in post.tags %}
                      <a href="{{ url_for('user_posts.tag', slug=tag.slug) }}" class="badge badge-{{tag.get_color()}}">
                          {{tag.name}}
                      </a>
                  {% endfor %}
                  </div>
              {% endif %}

              {% if post.category %}
                  <a class="post-category" href="{{ url_for('user_posts.category', slug=post.category.slug) }}">
                      {{ post.category.name }}
                  </a>
              {% endif %}

                <h3 class="post-title">
                    {{ post.title }}
                </h3>

                {{ post.text|safe }}

            </div>
        </article>
    </section>

    <section class="posts-another">
        <h2 class="d-none">Another posts</h2>

        <div class="container">
            <div class="posts-another-content row">
                <h3 class="posts-another-header col-12 text-xs-center">last posts</h3>

                {% for another_post in posts %}
                <article class="card col-12 col-md-4">
                  {% if another_post.photo %}
                    <img class="card-img-top img-fluid" src="/static/{{ another_post.photo }}" alt="{{another_post.title}}">
                  {% endif %}

                    <h4 class="posts-another-name">
                      <a href="{{ url_for('user_posts.detail', slug=another_post.slug) }}">{{another_post.title}}</a>
                    </h4>
                </article>
                {% endfor %}
            </div>
        </div>
    </section>

    <section class="comments container">
        <h2 class="d-none">Comments</h2>
            <div class="comments-content">
                <span class="comments-header">{{ post.comments|length }} Comments</span>

                {% for comment in post.comments %}
                <div class="media">
                    <img src="/static/app/image/user3.png" class="mr-5" alt="Photo of user">
                    <div class="media-body">
                        <h5 class="mt-0 comment-user">{{ comment.author.username }}</h5>
                        <p class="comment-text">
                            {{ comment.text|safe }}
                        </p>
                    </div>
                </div>
                {% endfor %}

                {% if current_user.is_authenticated %}
                <div class="media">
                    <img src="/static/app/image/user3.png" class="mr-5" alt="Photo of user">
                    <div class="media-body">
                        <form class="edit" action="{{ url_for('user_posts.detail', slug=post.slug) }}" method="POST">
                            {{ form.csrf_token }}
                  
                            {% for field in form %}
                  
                            <div class="form-group">
                                {{ field(class='comment-field-text') }}
                            </div>
                  
                            {% endfor %}
                  
                            <button class="btn btn-primary btn-user btn-block">Отправить</button>
                        </form>
                    </div>
                </div>
                {% endif %}
            </div>
    </section>
  </main>

    {{ ckeditor.load() }}
    {{ ckeditor.config(name='body') }}
{% endblock %}

project/templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block body %}

<main>
  <section class="container single-post">

    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Редактирование поста</h6>
      </div>

      <div class="card-body">
        <form class="edit" action="{{ url_for('user_posts.edit', slug=post.slug) }}" method="POST" enctype="multipart/form-data">
          {{ form.csrf_token }}

          {% for field in form %}

          <div class="form-group">

            {% if field.type == "BooleanField" %}
              <div class="custom-control custom-checkbox">
                {{ field(class='custom-control-input') }}
                {{ field.label(class='custom-control-label') }}
              </div>
            {% elif field.type == "QuerySelectMultipleField" %}
              {{ field.label(class='form-control-file') }}

              {% for subfield in field %}
                <div class="custom-control custom-checkbox">
                  {{ subfield(class='custom-control-input') }}
                  {{ subfield.label(class='custom-control-label') }}
                </div>
              {% endfor %}
            {% elif field.type == "MultiCheckboxField" %}
              {{ field.label(class='form-control-file') }}

              {{ field() }}

              {% for tag in field %}
                {{ tag.label() }}
                {{ tag }}
              {% endfor %}

              {% for (value, tag) in field.choices %}
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="tag{{value}}" name="tags" value="{{ value }}">
                  <label class="custom-control-label" for="tag{{value}}">{{ tag.name }}</label>
                </div>
              {% endfor %}
            {% elif field.type == "FileField" %}
                {{ field.label(class='form-control-file') }}
                {{ field() }}
            {% else %}
              {{ field.label() }}
              {{ field(class='form-control') }}
            {% endif %}
          </div>

          {% endfor %}

          <button class="btn btn-primary btn-user btn-block">Сохранить</button>
        </form>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
      </div>
    </div>

  </section>
</main>
{% endblock %}

project/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Посты
{% endblock %}

{% block body %}
  <div class="container posts mt-2">
      <!-- Page Heading -->
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{{ url_for('user_posts.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Добавить пост</a>
      </div>

      <!-- Content Row -->
      <div class="row">
        <div class="col-lg-12 mb-4">
          <!-- Illustrations -->
          {% for post in pages.items %}
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary float-left">
                {{ post.title }}
              </h6>

              <div class="float-right">
                <a href="{{ url_for('user_posts.detail', slug=post.slug) }}" class="btn btn-primary btn-sm btn-icon-split">
                  <span class="icon text-white">
                    <i class="fas fa-eye"></i>
                  </span>
                </a>
    
                <a href="{{ url_for('user_posts.edit', slug=post.slug) }}" class="btn btn-warning btn-sm btn-icon-split">
                  <span class="icon text-white">
                    <i class="fas fa-edit"></i>
                  </span>
                </a>
    
                <a href="{{ url_for('user_posts.delete', id=post.id) }}" class="btn btn-danger btn-sm btn-icon-split">
                  <span class="icon text-white">
                    <i class="fas fa-trash-alt"></i>
                  </span>
                </a>
              </div>
            </div>
            <div class="card-body">
              {% if post.photo %}
              <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
                  src="/static/{{ post.photo }}" alt="{{post.title}}">
              {% endif %}

              <p>{{ post.text|safe|truncate(150) }}</a>
            </div>
          </div>
          {% endfor %}
        </div>

        <nav class="col-lg-12 mb-4">
          <ul class="pagination">

            <li {% if not pages.has_prev %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
              <a class="page-link" href="./?page={{ pages.prev_num }}">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>

            {% for page in pages.iter_pages() %}
              <li {% if page == pages.page %}class="page-item active"{% else %}class="page-item"{% endif %}>
                <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
              </li>
            {% endfor %}

            <li {% if not pages.has_next %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
              <a class="page-link" href="./?page={{ pages.next_num }}">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
{% endblock %}