project/admin/tags/forms.py
from wtforms import Form, StringField, RadioField
from models.tag import COLORS


class TagForm(Form):
    name = StringField('Название')
    color = RadioField('Цвет', choices=COLORS)

project/admin/tags/blueprint.py
from flask import Blueprint, render_template
from flask import request, flash
from flask import redirect, url_for
from flask_security import login_required

from models.tag import Tag
from .forms import TagForm

from shared import db

tags = Blueprint('tags', __name__)


@tags.route('/')
@login_required
def index():
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    tags = Tag.query.order_by(Tag.id.desc())
    pages = tags.paginate(page=page, per_page=10)

    return render_template('tags/index.html', pages=pages)


@tags.route('/create', methods=['POST', 'GET'])
@login_required
def create():

    if request.method == 'POST':

        name = request.form['name']
        color = request.form['color']

        try:
            tag = Tag(name=name, color=color)
            db.session.add(tag)
            db.session.commit()
            return redirect(url_for('tags.index'))
        except Exception as exc:
            db.session.rollback()
            flash(exc.message, 'danger')
            print('Error', exc)

    form = TagForm()
    return render_template('tags/create.html', form=form)


@tags.route('/<id>/edit', methods=['POST', 'GET'])
@login_required
def edit(id):
    tag = Tag.query.filter(Tag.id == id).first()

    if request.method == 'POST':
        form = TagForm(formdata=request.form, obj=tag)
        form.populate_obj(tag)
        db.session.commit()
        return redirect(url_for('tags.index'))

    form = TagForm(obj=tag)
    return render_template('tags/edit.html', tag=tag, form=form)


@tags.route('/<id>/delete')
@login_required
def delete(id):
    Tag.query.filter(Tag.id == id).delete()
    db.session.commit()
    flash('Тэг удален', 'success')
    return redirect(url_for('tags.index'))

project/admin/templates/tags/create.html
{% extends 'admin/base.html' %}

{% block title %}
  Добавление тега
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Теги</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Добавление тега</h6>
          </div>
          <div class="card-body">
            

            <form class="user" action="{{ url_for('tags.create') }}" method="POST" enctype="multipart/form-data">
              {{ form.csrf_token }}

              {% for field in form %}

              <div class="form-group">
                {% if field.type == "RadioField" %}
                  {{ field.label() }}

                  {% for subfield in field %}
                    <div class="custom-control custom-radio mb-2">
                      {{ subfield(class='custom-control-input') }}

                      {{ subfield.label(class='custom-control-label badge badge-'+subfield.label.text) }}
                    </div>
                  {% endfor %}
                {% else %}
                  {{ field.label() }}
                  {{ field(class='form-control') }}
                {% endif %}
              </div>

              {% endfor %}

              <button class="btn btn-primary btn-user btn-block">Сохранить</button>
            
            </form>

            {{ ckeditor.load() }}
            {{ ckeditor.config(name='body') }}

          </div>
        </div>
      </div>
    </div>
{% endblock %}

project/admin/templates/tags/edit.html
{% extends 'admin/base.html' %}

{% block title %}
  {{ tag.name }}
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Теги</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Редактирование тега</h6>
          </div>
          <div class="card-body">
            

            <form class="user" action="{{ url_for('tags.edit', id=tag.id) }}" method="POST" enctype="multipart/form-data">
              {{ form.csrf_token }}

              {% for field in form %}

              <div class="form-group">
                {% if field.type == "RadioField" %}
                  {{ field.label() }}

                  {% for subfield in field %}
                    <div class="custom-control custom-radio mb-2">
                      {{ subfield(class='custom-control-input') }}

                      {{ subfield.label(class='custom-control-label badge badge-'+subfield.label.text) }}
                    </div>
                  {% endfor %}
                {% else %}
                  {{ field.label() }}
                  {{ field(class='form-control') }}
                {% endif %}
              </div>

              {% endfor %}

              <button class="btn btn-primary btn-user btn-block">Сохранить</button>
            
            </form>

            {{ ckeditor.load() }}
            {{ ckeditor.config(name='body') }}

          </div>
        </div>
      </div>
    </div>
{% endblock %}

project/admin/templates/tags/index.html
{% extends 'admin/base.html' %}

{% block title %}
    Теги
{% endblock %}

{% block body %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Теги</h1>
      <a href="{{ url_for('tags.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Добавить тег
      </a>
    </div>

    <!-- Content Row -->
    <div class="row">
      <table class="table col-lg-6">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Цвет</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for tag in pages.items %}
          <tr>
            <th scope="row">{{ tag.id }}</th>
            <td>{{ tag.name }}</td>
            <td>
              <span class="btn btn-{{ tag.get_color() }} btn-circle btn-sm"></span>
            </td>
            <td>
              <div class="btn-group btn-group-sm float-right" role="group" aria-label="...">
                <a href="{{ url_for('tags.edit', id=tag.id) }}" class="btn btn-warning btn-sm btn-icon-split">
                  <span class="text-white">
                    <i class="fas fa-edit"></i>
                  </span>
                </a>
    
                <a href="{{ url_for('tags.delete', id=tag.id) }}" class="btn btn-danger btn-sm btn-icon-split">
                  <span class="text-white">
                    <i class="fas fa-trash-alt"></i>
                  </span>
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
        </table>

      <nav class="col-lg-12 mb-4">
        <ul class="pagination">

          <li {% if not pages.has_prev %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.prev_num }}">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %}class="page-item active"{% else %}class="page-item"{% endif %}>
              <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
            </li>
          {% endfor %}

          <li {% if not pages.has_next %}class="page-item disabled"{% else %}class="page-item"{% endif %}>
            <a class="page-link" href="./?page={{ pages.next_num }}">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
{% endblock %}